server:
    port: 8083
    
eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka/
        register-with-eureka: true    

security:
    jwt:
        key-store: classpath:keystore.jks
        key-store-password: letmein
        key-pair-alias: mytestkey
        key-pair-password: changeme

spring:
    application:
        name: auth-server
        
    jackson:
        serialization:
            INDENT_OUTPUT: true
  
    # Database
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/testetoken
        username: postgres
        password: postgres
        
    # JPA properties
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true  
                dialect: org.hibernate.dialect.PostgreSQLDialect    
